name: eshop
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 #To Dependency
  get: ^4.3.4
  path_provider: ^2.0.4
  #Functional programming 
  dartz: ^0.10.0
  # service 
  get_it: ^7.2.0
  #state management
  flutter_bloc: ^8.0.1
  #Remote API
  http: ^0.13.3
  #value Equality
  equatable: ^2.0.3
  #local cache Local Database
  shared_preferences: ^2.0.7
  hive: ^2.0.6
  # for form 
  formz: ^0.4.1
  # Toast Notice
  fluttertoast: ^8.0.8
  # permission 
  permission_handler: ^8.1.6
  #firebase 
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  #
  cloud_firestore: ^2.5.3

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  # bloc_test: ^9.0.2
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.2.0

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/Product/
     - assets/DefaultProfile/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
